# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Seeff.BOSSDesktopv1
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: Seeff
PackageName: BOSS Desktop v1
License: All rights reserved
ShortDescription: This Windows application is a single place to access all the back office tools Seeff offer.
ManifestType: defaultLocale
ManifestVersion: 1.4.0
